apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wuda-chart.fullname" . }}-database-deployment
  labels:
    {{ include "wuda-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.database.replicas }}
  selector:
    matchLabels:
      {{ include "wuda-chart.selectorLabels" . | nindent 6 }}
      tier: database
  template:
    metadata:
      labels:
        {{ include "wuda-chart.labels" . | nindent 8 }}
        tier: database
    spec:
      containers:
      - name: {{ .Chart.Name }}-database
        image: "postgres:latest"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: alamakota
          - name: POSTGRES_USER
            value: board_games
          - name: POSTGRES_DB
            value: games