apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wuda-chart.fullname" . }}-backend-deployment
  labels:
    {{ include "wuda-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{ include "wuda-chart.selectorLabels" . | nindent 6 }}
      tier: backend
  template:
    metadata:
      labels:
        {{ include "wuda-chart.labels" . | nindent 8 }}
        tier: backend
    spec:
      containers:
      - name: {{ .Chart.Name }}-backend
        image: "{{ .Values.backend.image.repository  }}:{{ .Values.backend.image.tag }}"
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /liveness
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 3
        env:
          - name: POSTGRES_DB
            value: "games"
          - name: POSTGRES_USER
            value: "board_games"
          - name: POSTGRES_PASSWORD
            value: "alamakota"
          - name: POSTGRES_HOST
            value: "{{ include "wuda-chart.fullname" . }}-database-service"
          - name: PORT
            value: "5000"
          - name: JWT_KEY
            value: "your_secret_jwt_key"
          - name: APP_PORT
            value: "5000"